export type CircuitHighlight = {
  label: string;
  value: string;
  description: string;
};

export type CircuitStat = {
  label: string;
  value: string;
};

export type CircuitPageData = {
  slug: string;
  grandPrix: string;
  circuitName: string;
  location: string;
  country: string;
  roundDate: string;
  seasonPhase: string;
  accentColor: string;
  gradient: string;
  image: string;
  lapRecord: string;
  length: string;
  laps: string;
  firstGrandPrix: string;
  metaDescription: string;
  summary: string[];
  stats: CircuitStat[];
  highlights: CircuitHighlight[];
};

export const circuitPages: Record<string, CircuitPageData> = {
  melbourne: {
    slug: "melbourne",
    grandPrix: "Grand Prix d'Australie",
    circuitName: "Albert Park",
    location: "Melbourne",
    country: "Australie",
    roundDate: "8 mars 2026",
    seasonPhase: "Debut de saison",
    accentColor: "#0E7490",
    gradient: "linear-gradient(90deg,#031926 0%,#0B3B5A 25%,#0E7490 65%,#67E8F9 100%)",
    image: "/circuits/australie.webp",
    lapRecord: "1:19.813",
    length: "5,278 km",
    laps: "58",
    firstGrandPrix: "1996",
    metaDescription: "Grand Prix d'Australie à Albert Park (Melbourne) le 8 mars 2026 : le circuit urbain rapide qui ouvre la saison F1 2026.",
    summary: [
      "Melbourne ouvre la saison 2026 avec le decor urbain rapide et spectaculaire d'Albert Park.",
      "Le trace combine longues accelerations, gros freinages et sections fluides qui exigent un bon compromis aerodynamique.",
      "C'est un rendez-vous fort en ambiance, souvent marque par des relances et un week-end tres suivi des le debut du championnat.",
    ],
    stats: [
      { label: "Longueur", value: "5,278 km" },
      { label: "Tours", value: "58" },
      { label: "Record du tour", value: "1:19.813" },
      { label: "Premier GP", value: "1996" },
    ],
    highlights: [
      { label: "Profil", value: "Urbain rapide", description: "Des murs proches et plusieurs zones de DRS rendent la moindre erreur couteuse." },
      { label: "Enjeu", value: "Ouverture 2026", description: "Premier grand test grandeur nature pour les equipes et les rookies." },
      { label: "Ambiance", value: "Tres forte", description: "Le public australien lance traditionnellement l'energie de la saison." },
    ],
  },
  shanghai: {
    slug: "shanghai",
    grandPrix: "Grand Prix de Chine",
    circuitName: "Circuit international de Shanghai",
    location: "Shanghai",
    country: "Chine",
    roundDate: "15 mars 2026",
    seasonPhase: "Debut de saison",
    accentColor: "#DC2626",
    gradient: "linear-gradient(90deg,#220A0A 0%,#7F1D1D 30%,#DC2626 65%,#FCA5A5 100%)",
    image: "/circuits/chine.webp",
    lapRecord: "1:32.238",
    length: "5,451 km",
    laps: "56",
    firstGrandPrix: "2004",
    metaDescription: "Grand Prix de Chine sur le circuit international de Shanghai le 15 mars 2026 : un tracé technique et exigeant en début de saison F1.",
    summary: [
      "Shanghai revient tres tot dans la saison 2026 avec son trace vaste et tres technique.",
      "Le premier virage en spirale et l'immense ligne droite opposee mettent a l'epreuve le train avant comme la vitesse de pointe.",
      "C'est un circuit qui recompense les monoplaces equilibrees et les pilotes capables de gerer proprement leurs pneus avant.",
    ],
    stats: [
      { label: "Longueur", value: "5,451 km" },
      { label: "Tours", value: "56" },
      { label: "Record du tour", value: "1:32.238" },
      { label: "Premier GP", value: "2004" },
    ],
    highlights: [
      { label: "Signature", value: "Virages 1-2", description: "Une entree interminable qui punit les voitures sous-vireuses." },
      { label: "Depassement", value: "T14", description: "Le gros freinage de l'epingle reste le point chaud principal." },
      { label: "Lecture", value: "Circuit complet", description: "Traction, aero et gestion des pneus y comptent tous." },
    ],
  },
  suzuka: {
    slug: "suzuka",
    grandPrix: "Grand Prix du Japon",
    circuitName: "Suzuka",
    location: "Suzuka",
    country: "Japon",
    roundDate: "29 mars 2026",
    seasonPhase: "Debut de saison",
    accentColor: "#2563EB",
    gradient: "linear-gradient(90deg,#0B1020 0%,#1D4ED8 35%,#2563EB 65%,#93C5FD 100%)",
    image: "/circuits/japon.webp",
    lapRecord: "1:30.983",
    length: "5,807 km",
    laps: "53",
    firstGrandPrix: "1987",
    metaDescription: "Grand Prix du Japon à Suzuka le 29 mars 2026 : le mythique circuit en huit, ses esses rapides et le célèbre virage 130R.",
    summary: [
      "Suzuka reste l'un des circuits les plus respectes du calendrier avec ses esses rapides et son celebre 130R.",
      "Le trace en huit demande precision, engagement et grande confiance dans l'avant de la voiture.",
      "Les pilotes y font souvent la difference tant la piste sanctionne les approximations sur toute sa longueur.",
    ],
    stats: [
      { label: "Longueur", value: "5,807 km" },
      { label: "Tours", value: "53" },
      { label: "Record du tour", value: "1:30.983" },
      { label: "Premier GP", value: "1987" },
    ],
    highlights: [
      { label: "Reference", value: "Esses du S1", description: "Une sequence qui mesure la confiance du pilote et l'agilite du chassis." },
      { label: "Mythe", value: "130R", description: "L'un des virages rapides les plus emblématiques de la F1 moderne." },
      { label: "Exigence", value: "Tres haute", description: "Peu de repos, peu d'erreurs permises et beaucoup de rythme." },
    ],
  },
  sakhir: {
    slug: "sakhir",
    grandPrix: "Grand Prix de Bahrein",
    circuitName: "Bahrain International Circuit",
    location: "Sakhir",
    country: "Bahrein",
    roundDate: "12 avril 2026",
    seasonPhase: "Moyen-Orient & Ameriques",
    accentColor: "#D97706",
    gradient: "linear-gradient(90deg,#2A1400 0%,#92400E 30%,#D97706 65%,#FCD34D 100%)",
    image: "/circuits/bahrein.webp",
    lapRecord: "1:31.447",
    length: "5,412 km",
    laps: "57",
    firstGrandPrix: "2004",
    metaDescription: "Grand Prix de Bahreïn à Sakhir le 12 avril 2026 : piste abrasive et stratégique, référence pour juger le vrai rythme de course.",
    summary: [
      "Sakhir propose une piste abrasive, large et tres utile pour comparer les rythmes de course.",
      "La traction en sortie lente et la gestion thermique des pneus y jouent un role central.",
      "Sous les projecteurs, Bahrein offre regulierement des strategies interessantes et plusieurs opportunites de depassement.",
    ],
    stats: [
      { label: "Longueur", value: "5,412 km" },
      { label: "Tours", value: "57" },
      { label: "Record du tour", value: "1:31.447" },
      { label: "Premier GP", value: "2004" },
    ],
    highlights: [
      { label: "Sol", value: "Abrasif", description: "Les pneus arriere souffrent vite sur les sorties des virages lents." },
      { label: "DRS", value: "Tres efficace", description: "Les attaques s'organisent surtout vers les virages 1 et 4." },
      { label: "Lecture", value: "Course", description: "Un rendez-vous ideal pour juger le vrai rythme d'une voiture." },
    ],
  },
  djeddah: {
    slug: "djeddah",
    grandPrix: "Grand Prix d'Arabie saoudite",
    circuitName: "Jeddah Corniche Circuit",
    location: "Djeddah",
    country: "Arabie saoudite",
    roundDate: "19 avril 2026",
    seasonPhase: "Moyen-Orient & Ameriques",
    accentColor: "#0F766E",
    gradient: "linear-gradient(90deg,#03201E 0%,#115E59 30%,#0F766E 65%,#5EEAD4 100%)",
    image: "/circuits/arabie%20saoudite.webp",
    lapRecord: "1:30.734",
    length: "6,174 km",
    laps: "50",
    firstGrandPrix: "2021",
    metaDescription: "Grand Prix d'Arabie saoudite à Djeddah le 19 avril 2026 : le circuit urbain le plus rapide du calendrier de Formule 1.",
    summary: [
      "Djeddah est un trace urbain ultra-rapide, bordure de murs et rythmes tres eleves compris.",
      "La moindre erreur y coute cher, surtout dans les enchainements a haute vitesse qui laissent peu de marge.",
      "Ce circuit met en avant l'efficacite aerodynamique et le sang-froid dans le trafic comme sous safety car.",
    ],
    stats: [
      { label: "Longueur", value: "6,174 km" },
      { label: "Tours", value: "50" },
      { label: "Record du tour", value: "1:30.734" },
      { label: "Premier GP", value: "2021" },
    ],
    highlights: [
      { label: "Vitesse", value: "Tres elevee", description: "L'un des circuits urbains les plus rapides jamais vus en F1." },
      { label: "Risque", value: "Murs proches", description: "Les trajectoires se jouent souvent a quelques centimetres." },
      { label: "Scenario", value: "Imprevisible", description: "Neutralisations et incidents peuvent renverser une course." },
    ],
  },
  miami: {
    slug: "miami",
    grandPrix: "Grand Prix de Miami",
    circuitName: "Miami International Autodrome",
    location: "Miami",
    country: "Etats-Unis",
    roundDate: "3 mai 2026",
    seasonPhase: "Moyen-Orient & Ameriques",
    accentColor: "#0891B2",
    gradient: "linear-gradient(90deg,#082F49 0%,#0E7490 30%,#0891B2 65%,#67E8F9 100%)",
    image: "/circuits/miami.webp",
    lapRecord: "1:29.708",
    length: "5,412 km",
    laps: "57",
    firstGrandPrix: "2022",
    metaDescription: "Grand Prix de Miami le 3 mai 2026 : circuit semi-urbain rapide et ambiance très événementielle au cœur de la Floride.",
    summary: [
      "Miami melange longues lignes droites, gros freinages et une section plus lente autour du stade.",
      "Le circuit favorise les voitures efficaces en pointe mais capables aussi de bien relancer dans le secteur sinueux.",
      "Avec son ambiance tres evenementielle, c'est devenu un rendez-vous majeur de la partie americaine du calendrier.",
    ],
    stats: [
      { label: "Longueur", value: "5,412 km" },
      { label: "Tours", value: "57" },
      { label: "Record du tour", value: "1:29.708" },
      { label: "Premier GP", value: "2022" },
    ],
    highlights: [
      { label: "Style", value: "Semi-urbain", description: "La piste offre des profils de virages tres differents d'un secteur a l'autre." },
      { label: "Piste", value: "Large", description: "Plusieurs freinages invitent aux attaques tardives." },
      { label: "Tempo", value: "Show US", description: "L'evenement compte autant par l'ambiance que par le sport." },
    ],
  },
  montreal: {
    slug: "montreal",
    grandPrix: "Grand Prix du Canada",
    circuitName: "Circuit Gilles-Villeneuve",
    location: "Montreal",
    country: "Canada",
    roundDate: "24 mai 2026",
    seasonPhase: "Moyen-Orient & Ameriques",
    accentColor: "#1D4ED8",
    gradient: "linear-gradient(90deg,#111827 0%,#1E3A8A 30%,#1D4ED8 65%,#93C5FD 100%)",
    image: "/circuits/canada.webp",
    lapRecord: "1:13.078",
    length: "4,361 km",
    laps: "70",
    firstGrandPrix: "1978",
    metaDescription: "Grand Prix du Canada au circuit Gilles-Villeneuve (Montréal) le 24 mai 2026 : chicanes, murs proches et le fameux mur des champions.",
    summary: [
      "Montreal est un classique adore pour ses chicanes, ses murs proches et ses gros freinages.",
      "Les monoplaces doivent bien grimper sur les vibreurs tout en restant stables au freinage et en traction.",
      "Le fameux mur des champions et les changements de rythme en font un circuit toujours vivant.",
    ],
    stats: [
      { label: "Longueur", value: "4,361 km" },
      { label: "Tours", value: "70" },
      { label: "Record du tour", value: "1:13.078" },
      { label: "Premier GP", value: "1978" },
    ],
    highlights: [
      { label: "Freinage", value: "Cle du tour", description: "Les attaques a la limite y rapportent gros mais coutent aussi tres cher." },
      { label: "Vibreurs", value: "Agressifs", description: "Le chassis doit encaisser les changements d'appui sur tout le tour." },
      { label: "Symbole", value: "Mur des champions", description: "Une sortie trop large peut y ruiner un week-end en un instant." },
    ],
  },
  monaco: {
    slug: "monaco",
    grandPrix: "Grand Prix de Monaco",
    circuitName: "Circuit de Monaco",
    location: "Monaco",
    country: "Monaco",
    roundDate: "7 juin 2026",
    seasonPhase: "Saison europeenne",
    accentColor: "#7C3AED",
    gradient: "linear-gradient(90deg,#1E1B4B 0%,#5B21B6 30%,#7C3AED 65%,#C4B5FD 100%)",
    image: "/circuits/monaco.webp",
    lapRecord: "1:12.909",
    length: "3,337 km",
    laps: "78",
    firstGrandPrix: "1950",
    metaDescription: "Grand Prix de Monaco le 7 juin 2026 : le joyau historique de la Formule 1, ses rues étroites et son prestige inégalé.",
    summary: [
      "Monaco reste le joyau historique de la F1 avec sa piste etroite, ses rails et son prestige unique.",
      "La qualification y est souvent decisive, tant depasser en course reste complexe dans les rues de la Principaute.",
      "Precision absolue, confiance et courage sont les maitres-mots de ce week-end hors norme.",
    ],
    stats: [
      { label: "Longueur", value: "3,337 km" },
      { label: "Tours", value: "78" },
      { label: "Record du tour", value: "1:12.909" },
      { label: "Premier GP", value: "1950" },
    ],
    highlights: [
      { label: "Prestige", value: "Unique", description: "L'une des victoires les plus convoitees du championnat." },
      { label: "Qualifs", value: "Essentielles", description: "La pole y compte souvent encore plus qu'ailleurs." },
      { label: "Pilotage", value: "Millimetre", description: "Chaque tour est un exercice d'engagement pur entre les rails." },
    ],
  },
  barcelone: {
    slug: "barcelone",
    grandPrix: "Grand Prix d'Espagne",
    circuitName: "Circuit de Barcelona-Catalunya",
    location: "Barcelone",
    country: "Espagne",
    roundDate: "14 juin 2026",
    seasonPhase: "Saison europeenne",
    accentColor: "#B91C1C",
    gradient: "linear-gradient(90deg,#2A0A0A 0%,#7F1D1D 30%,#B91C1C 65%,#FCA5A5 100%)",
    image: "/circuits/barcelone.webp",
    lapRecord: "1:16.330",
    length: "4,657 km",
    laps: "66",
    firstGrandPrix: "1991",
    metaDescription: "Grand Prix d'Espagne au circuit de Barcelona-Catalunya le 14 juin 2026 : la référence technique pour juger une monoplace.",
    summary: [
      "Barcelone est depuis longtemps une reference technique pour juger l'equilibre general d'une monoplace.",
      "Les virages rapides du premier secteur et les exigences aero du reste du tour en font une piste complete.",
      "Quand une voiture est performante a Barcelone, cela dit souvent beaucoup sur son potentiel global.",
    ],
    stats: [
      { label: "Longueur", value: "4,657 km" },
      { label: "Tours", value: "66" },
      { label: "Record du tour", value: "1:16.330" },
      { label: "Premier GP", value: "1991" },
    ],
    highlights: [
      { label: "Lecture", value: "Tres complete", description: "Appui, usure pneu et qualite du train avant y sont bien visibles." },
      { label: "Reference", value: "Technique", description: "C'est l'un des barometres historiques de performance en F1." },
      { label: "Europe", value: "Lancement", description: "Le GP marque traditionnellement l'entree dans le coeur de la saison europeenne." },
    ],
  },
  spielberg: {
    slug: "spielberg",
    grandPrix: "Grand Prix d'Autriche",
    circuitName: "Red Bull Ring",
    location: "Spielberg",
    country: "Autriche",
    roundDate: "28 juin 2026",
    seasonPhase: "Saison europeenne",
    accentColor: "#1D4ED8",
    gradient: "linear-gradient(90deg,#111827 0%,#1E3A8A 30%,#1D4ED8 65%,#60A5FA 100%)",
    image: "/circuits/autriche.webp",
    lapRecord: "1:05.619",
    length: "4,318 km",
    laps: "71",
    firstGrandPrix: "1970",
    metaDescription: "Grand Prix d'Autriche au Red Bull Ring (Spielberg) le 28 juin 2026 : circuit court, nerveux et intense en pleine montagne.",
    summary: [
      "Spielberg est court, nerveux et tres intense, avec trois gros freinages qui rythment le premier demi-tour.",
      "Le relief et les ecarts souvent tres faibles rendent les qualifications particulierement serrees.",
      "La piste encourage les attaques, surtout quand le DRS et la traction fonctionnent bien.",
    ],
    stats: [
      { label: "Longueur", value: "4,318 km" },
      { label: "Tours", value: "71" },
      { label: "Record du tour", value: "1:05.619" },
      { label: "Premier GP", value: "1970" },
    ],
    highlights: [
      { label: "Format", value: "Court", description: "Les tours rapides concentrent vite le peloton en qualifs." },
      { label: "Relief", value: "Marque", description: "Les montees et descentes ajoutent du caractere au trace." },
      { label: "Attaque", value: "Freinages 1-3", description: "C'est la zone la plus chaude pour tenter un depassement." },
    ],
  },
  silverstone: {
    slug: "silverstone",
    grandPrix: "Grand Prix de Grande-Bretagne",
    circuitName: "Silverstone",
    location: "Silverstone",
    country: "Royaume-Uni",
    roundDate: "5 juillet 2026",
    seasonPhase: "Saison europeenne",
    accentColor: "#2563EB",
    gradient: "linear-gradient(90deg,#0F172A 0%,#1D4ED8 30%,#2563EB 65%,#93C5FD 100%)",
    image: "/circuits/royaume-uni.webp",
    lapRecord: "1:27.097",
    length: "5,891 km",
    laps: "52",
    firstGrandPrix: "1950",
    metaDescription: "Grand Prix de Grande-Bretagne à Silverstone le 5 juillet 2026 : Maggots, Becketts et Copse, le temple de la vitesse pure.",
    summary: [
      "Silverstone est l'un des temples de la vitesse pure avec Maggots, Becketts et Copse comme signatures absolues.",
      "Les appuis, la confiance a haute vitesse et la stabilite dans les changements de direction y sont essentiels.",
      "Le public britannique et l'histoire du lieu donnent toujours une dimension speciale a ce Grand Prix.",
    ],
    stats: [
      { label: "Longueur", value: "5,891 km" },
      { label: "Tours", value: "52" },
      { label: "Record du tour", value: "1:27.097" },
      { label: "Premier GP", value: "1950" },
    ],
    highlights: [
      { label: "ADN", value: "Haute vitesse", description: "Les grands enchainements aero y definissent la qualite d'une voiture." },
      { label: "Histoire", value: "Fondatrice", description: "Silverstone a accueilli le tout premier GP de l'histoire du championnat." },
      { label: "Public", value: "Passionne", description: "L'ambiance du week-end figure parmi les plus fortes de la saison." },
    ],
  },
  spa: {
    slug: "spa",
    grandPrix: "Grand Prix de Belgique",
    circuitName: "Spa-Francorchamps",
    location: "Spa-Francorchamps",
    country: "Belgique",
    roundDate: "19 juillet 2026",
    seasonPhase: "Saison europeenne",
    accentColor: "#0F766E",
    gradient: "linear-gradient(90deg,#052E2B 0%,#115E59 30%,#0F766E 65%,#99F6E4 100%)",
    image: "/circuits/belgique.webp",
    lapRecord: "1:46.286",
    length: "7,004 km",
    laps: "44",
    firstGrandPrix: "1950",
    metaDescription: "Grand Prix de Belgique à Spa-Francorchamps le 19 juillet 2026 : Eau Rouge, Raidillon et Pouhon, circuit mythique et vallonné.",
    summary: [
      "Spa est une piste longue, vallonnee et imprevisible, adoree pour son caractere naturel.",
      "Eau Rouge, Raidillon, Pouhon ou Blanchimont en font un test complet de courage et d'efficacite aero.",
      "La meteo peut y basculer rapidement d'un secteur a l'autre et changer totalement la lecture du week-end.",
    ],
    stats: [
      { label: "Longueur", value: "7,004 km" },
      { label: "Tours", value: "44" },
      { label: "Record du tour", value: "1:46.286" },
      { label: "Premier GP", value: "1950" },
    ],
    highlights: [
      { label: "Nature", value: "Circuit mythique", description: "Le relief et la longueur donnent un cachet introuvable ailleurs." },
      { label: "Meteo", value: "Changeante", description: "Le choix des reglages et des pneus y devient souvent delicat." },
      { label: "Reference", value: "Pilotes", description: "La piste continue de faire partie des grands juges du talent pur." },
    ],
  },
  budapest: {
    slug: "budapest",
    grandPrix: "Grand Prix de Hongrie",
    circuitName: "Hungaroring",
    location: "Budapest",
    country: "Hongrie",
    roundDate: "26 juillet 2026",
    seasonPhase: "Saison europeenne",
    accentColor: "#E11D48",
    gradient: "linear-gradient(90deg,#3B0A1B 0%,#9F1239 30%,#E11D48 65%,#FDA4AF 100%)",
    image: "/circuits/hongrie.webp",
    lapRecord: "1:16.627",
    length: "4,381 km",
    laps: "70",
    firstGrandPrix: "1986",
    metaDescription: "Grand Prix de Hongrie au Hungaroring (Budapest) le 26 juillet 2026 : un tracé technique et sinueux, souvent comparé à Monaco.",
    summary: [
      "Le Hungaroring est souvent compare a un Monaco sans murs, tant l'enchainement est dense et technique.",
      "L'appui, l'agilite et la qualite des qualifications y ont une importance capitale.",
      "Sous la chaleur de l'ete, la gestion des pneus et la proprete dans le trafic deviennent decisives.",
    ],
    stats: [
      { label: "Longueur", value: "4,381 km" },
      { label: "Tours", value: "70" },
      { label: "Record du tour", value: "1:16.627" },
      { label: "Premier GP", value: "1986" },
    ],
    highlights: [
      { label: "Style", value: "Technique", description: "Le rythme est constant et la piste laisse peu de vrais temps morts." },
      { label: "Qualifs", value: "Cruciales", description: "Bien se placer sur la grille reste souvent la cle du dimanche." },
      { label: "Chaleur", value: "Facteur", description: "Les conditions estivales mettent a rude epreuve pneus et pilotes." },
    ],
  },
  zandvoort: {
    slug: "zandvoort",
    grandPrix: "Grand Prix des Pays-Bas",
    circuitName: "Circuit Zandvoort",
    location: "Zandvoort",
    country: "Pays-Bas",
    roundDate: "23 aout 2026",
    seasonPhase: "Saison europeenne",
    accentColor: "#F97316",
    gradient: "linear-gradient(90deg,#431407 0%,#C2410C 30%,#F97316 65%,#FDBA74 100%)",
    image: "/circuits/pays-bas.webp",
    lapRecord: "1:11.097",
    length: "4,259 km",
    laps: "72",
    firstGrandPrix: "1952",
    metaDescription: "Grand Prix des Pays-Bas à Zandvoort le 23 août 2026 : virages relevés, tracé compact et ambiance orange électrique.",
    summary: [
      "Zandvoort est compact, vallonne et tres spectaculaire avec ses virages releves et son ruban tres etroit.",
      "La qualite du train avant et la precision dans les appuis comptent enormement sur ce trace unique.",
      "L'atmosphere neerlandaise donne souvent une vraie identite visuelle et sonore a ce rendez-vous d'aout.",
    ],
    stats: [
      { label: "Longueur", value: "4,259 km" },
      { label: "Tours", value: "72" },
      { label: "Record du tour", value: "1:11.097" },
      { label: "Premier GP", value: "1952" },
    ],
    highlights: [
      { label: "Courbes", value: "Inclinees", description: "Les banking de Zandvoort changent totalement le ressenti du pilotage." },
      { label: "Flux", value: "Continu", description: "Le circuit recompense les pilotes capables de garder beaucoup de vitesse." },
      { label: "Ambiance", value: "Orange", description: "Le public neerlandais transforme le site en chaudron." },
    ],
  },
  monza: {
    slug: "monza",
    grandPrix: "Grand Prix d'Italie",
    circuitName: "Autodromo Nazionale Monza",
    location: "Monza",
    country: "Italie",
    roundDate: "Debut septembre 2026",
    seasonPhase: "Saison europeenne",
    accentColor: "#16A34A",
    gradient: "linear-gradient(90deg,#052E16 0%,#166534 30%,#16A34A 65%,#86EFAC 100%)",
    image: "/circuits/Italie.webp",
    lapRecord: "1:21.046",
    length: "5,793 km",
    laps: "53",
    firstGrandPrix: "1950",
    metaDescription: "Grand Prix d'Italie à Monza début septembre 2026 : le temple de la vitesse et l'émotion unique des tifosi pour Ferrari.",
    summary: [
      "Monza est le temple de la vitesse, avec un niveau d'appui minimal et de longues accelerations a pleine charge.",
      "Les freinages des chicanes et la traction en sortie y decident une grande partie du chrono.",
      "Chez les tifosi, ce Grand Prix porte toujours une charge emotionnelle unique pour Ferrari comme pour toute la F1.",
    ],
    stats: [
      { label: "Longueur", value: "5,793 km" },
      { label: "Tours", value: "53" },
      { label: "Record du tour", value: "1:21.046" },
      { label: "Premier GP", value: "1950" },
    ],
    highlights: [
      { label: "Appui", value: "Minimal", description: "L'efficacite en ligne droite est prioritaire presque partout." },
      { label: "Freinages", value: "Violents", description: "La stabilite au freinage fait gagner un temps precieux." },
      { label: "Emotion", value: "Tifosi", description: "Monza reste l'un des rendez-vous les plus fervents du calendrier." },
    ],
  },
  madrid: {
    slug: "madrid",
    grandPrix: "Grand Prix d'Espagne",
    circuitName: "Circuit urbain de Madrid",
    location: "Madrid",
    country: "Espagne",
    roundDate: "13 septembre 2026",
    seasonPhase: "Saison europeenne",
    accentColor: "#BE123C",
    gradient: "linear-gradient(90deg,#4C0519 0%,#9F1239 30%,#BE123C 65%,#FDA4AF 100%)",
    image: "/circuits/madrid.webp",
    lapRecord: "A definir",
    length: "A confirmer",
    laps: "A confirmer",
    firstGrandPrix: "2026",
    metaDescription: "Grand Prix d'Espagne à Madrid le 13 septembre 2026 : le tout nouveau circuit urbain qui fait son entrée au calendrier F1 2026.",
    summary: [
      "Madrid doit faire son entree au calendrier 2026 comme nouvelle etape espagnole du championnat.",
      "Le trace est presente ici comme un nouveau rendez-vous urbain, encore en phase de reference pour ses donnees definitives.",
      "Cette manche ajoute une vraie nouveaute a la saison europeenne et devrait attirer une forte attention mediatique.",
    ],
    stats: [
      { label: "Longueur", value: "A confirmer" },
      { label: "Tours", value: "A confirmer" },
      { label: "Record du tour", value: "A definir" },
      { label: "Premier GP", value: "2026" },
    ],
    highlights: [
      { label: "Nouveaute", value: "2026", description: "Le GP de Madrid est l'une des grandes nouveautes du calendrier." },
      { label: "Statut", value: "En attente", description: "Les chiffres de reference pourront evoluer a l'approche du week-end." },
      { label: "Impact", value: "Mediatique", description: "Le lancement du projet sera observe de tres pres en Espagne." },
    ],
  },
  bakou: {
    slug: "bakou",
    grandPrix: "Grand Prix d'Azerbaidjan",
    circuitName: "Baku City Circuit",
    location: "Bakou",
    country: "Azerbaidjan",
    roundDate: "Fin septembre 2026",
    seasonPhase: "Fin de saison",
    accentColor: "#0EA5E9",
    gradient: "linear-gradient(90deg,#082F49 0%,#0369A1 30%,#0EA5E9 65%,#BAE6FD 100%)",
    image: "/circuits/azerbaidjan.webp",
    lapRecord: "1:43.009",
    length: "6,003 km",
    laps: "51",
    firstGrandPrix: "2016",
    metaDescription: "Grand Prix d'Azerbaïdjan à Bakou fin septembre 2026 : contraste unique entre ruelles étroites et immense ligne droite au bord de la Caspienne.",
    summary: [
      "Bakou combine un secteur historique et tres etroit avec une immense ligne droite au bord de la mer Caspienne.",
      "Ce contraste rend le circuit unique et souvent tres spectaculaire, entre precision lente et vitesse maximale.",
      "Les safety cars et les retournements de situation y sont frequents, surtout en fin de saison.",
    ],
    stats: [
      { label: "Longueur", value: "6,003 km" },
      { label: "Tours", value: "51" },
      { label: "Record du tour", value: "1:43.009" },
      { label: "Premier GP", value: "2016" },
    ],
    highlights: [
      { label: "Contraste", value: "Extreme", description: "Des murs serrés dans le vieux Bakou puis une enorme section a fond." },
      { label: "Chaos", value: "Possible", description: "Le circuit a souvent produit des courses imprevisibles." },
      { label: "Timing", value: "Fin de saison", description: "Chaque point peut y peser tres lourd au championnat." },
    ],
  },
  singapour: {
    slug: "singapour",
    grandPrix: "Grand Prix de Singapour",
    circuitName: "Marina Bay Street Circuit",
    location: "Singapour",
    country: "Singapour",
    roundDate: "Octobre 2026",
    seasonPhase: "Fin de saison",
    accentColor: "#7C3AED",
    gradient: "linear-gradient(90deg,#240046 0%,#5B21B6 30%,#7C3AED 65%,#DDD6FE 100%)",
    image: "/circuits/singapour.webp",
    lapRecord: "1:34.486",
    length: "4,928 km",
    laps: "62",
    firstGrandPrix: "2008",
    metaDescription: "Grand Prix de Singapour à Marina Bay en octobre 2026 : course nocturne sous forte chaleur et humidité, l'une des plus exigeantes de l'année.",
    summary: [
      "Singapour est l'un des week-ends les plus exigeants physiquement du calendrier avec chaleur, humidite et course nocturne.",
      "Le trace urbain demande traction, patience et une tres grande concentration du premier au dernier tour.",
      "En general, ce Grand Prix teste autant les pilotes que les machines et les equipes en strategie.",
    ],
    stats: [
      { label: "Longueur", value: "4,928 km" },
      { label: "Tours", value: "62" },
      { label: "Record du tour", value: "1:34.486" },
      { label: "Premier GP", value: "2008" },
    ],
    highlights: [
      { label: "Conditions", value: "Tres dures", description: "La chaleur humide use les pilotes sur la longueur." },
      { label: "Nuit", value: "Signature", description: "L'eclairage artificiel renforce le caractere du week-end." },
      { label: "Strategie", value: "Importante", description: "Neutralisations et degradation peuvent vite rebattre les cartes." },
    ],
  },
  austin: {
    slug: "austin",
    grandPrix: "Grand Prix des Etats-Unis",
    circuitName: "Circuit of the Americas",
    location: "Austin",
    country: "Etats-Unis",
    roundDate: "Octobre 2026",
    seasonPhase: "Fin de saison",
    accentColor: "#DC2626",
    gradient: "linear-gradient(90deg,#1F2937 0%,#7F1D1D 30%,#DC2626 65%,#FCA5A5 100%)",
    image: "/circuits/austin.webp",
    lapRecord: "1:36.169",
    length: "5,513 km",
    laps: "56",
    firstGrandPrix: "2012",
    metaDescription: "Grand Prix des États-Unis au Circuit of the Americas (Austin) en octobre 2026 : tracé moderne et grande ambiance texane.",
    summary: [
      "Austin est un circuit moderne qui emprunte des inspirations a plusieurs grands traces historiques.",
      "Le premier secteur rapide, la longue montee vers le virage 1 et les gros freinages en font une piste tres complete.",
      "Le COTA offre souvent de belles bagarres en piste et une ambiance americaine tres appuyee.",
    ],
    stats: [
      { label: "Longueur", value: "5,513 km" },
      { label: "Tours", value: "56" },
      { label: "Record du tour", value: "1:36.169" },
      { label: "Premier GP", value: "2012" },
    ],
    highlights: [
      { label: "Virage 1", value: "Iconique", description: "La montee et le gros freinage ouvrent souvent la voie a des duels." },
      { label: "Mix", value: "Complet", description: "Le circuit alterne appuis rapides et zones de freinage prononcees." },
      { label: "Public", value: "Massif", description: "C'est l'un des grands rendez-vous F1 aux Etats-Unis." },
    ],
  },
  mexico: {
    slug: "mexico",
    grandPrix: "Grand Prix du Mexique",
    circuitName: "Autodromo Hermanos Rodriguez",
    location: "Mexico",
    country: "Mexique",
    roundDate: "Octobre 2026",
    seasonPhase: "Fin de saison",
    accentColor: "#16A34A",
    gradient: "linear-gradient(90deg,#052E16 0%,#166534 30%,#16A34A 65%,#BBF7D0 100%)",
    image: "/circuits/mexique.webp",
    lapRecord: "1:17.774",
    length: "4,304 km",
    laps: "71",
    firstGrandPrix: "1963",
    metaDescription: "Grand Prix du Mexique à l'Autodromo Hermanos Rodríguez en octobre 2026 : course en altitude et passage mythique dans le stadium.",
    summary: [
      "Mexico se dispute en altitude, ce qui modifie fortement les besoins de refroidissement et d'appui aerodynamique.",
      "La tres longue ligne droite jusqu'au virage 1 genere souvent des attaques en paquet au depart.",
      "Le stadium et l'ambiance populaire donnent au week-end un cachet particulierement chaleureux.",
    ],
    stats: [
      { label: "Longueur", value: "4,304 km" },
      { label: "Tours", value: "71" },
      { label: "Record du tour", value: "1:17.774" },
      { label: "Premier GP", value: "1963" },
    ],
    highlights: [
      { label: "Altitude", value: "Exceptionnelle", description: "L'air rare change le comportement aero et moteur." },
      { label: "Depart", value: "Explosif", description: "La zone de freinage du virage 1 est souvent tres animee." },
      { label: "Ambiance", value: "Stadium", description: "Le passage dans l'enceinte est l'un des visuels forts de la saison." },
    ],
  },
  saopaulo: {
    slug: "saopaulo",
    grandPrix: "Grand Prix du Bresil",
    circuitName: "Interlagos",
    location: "Sao Paulo",
    country: "Bresil",
    roundDate: "Novembre 2026",
    seasonPhase: "Fin de saison",
    accentColor: "#EAB308",
    gradient: "linear-gradient(90deg,#3F2E00 0%,#A16207 30%,#EAB308 65%,#FDE68A 100%)",
    image: "/circuits/bresil.webp",
    lapRecord: "1:10.540",
    length: "4,309 km",
    laps: "71",
    firstGrandPrix: "1973",
    metaDescription: "Grand Prix du Brésil à Interlagos (Sao Paulo) en novembre 2026 : circuit court et chargé d'histoire, théâtre de grands duels pour le titre.",
    summary: [
      "Interlagos est un circuit court, bosselé et charge d'histoire, souvent theater de grandes batailles pour les titres.",
      "Le sens anti-horaire, les changements d'altitude et la meteo instable renforcent son caractere.",
      "Peu de circuits offrent une telle sensation d'urgence du debut a la fin du tour.",
    ],
    stats: [
      { label: "Longueur", value: "4,309 km" },
      { label: "Tours", value: "71" },
      { label: "Record du tour", value: "1:10.540" },
      { label: "Premier GP", value: "1973" },
    ],
    highlights: [
      { label: "Histoire", value: "Tres forte", description: "Interlagos a souvent decide ou bouleverse des championnats." },
      { label: "Meteo", value: "Vite changeante", description: "La pluie peut surgir et transformer totalement la course." },
      { label: "Rythme", value: "Sans pause", description: "Le tour est court, vivant et nerveux du premier virage au dernier." },
    ],
  },
  "las-vegas": {
    slug: "las-vegas",
    grandPrix: "Grand Prix de Las Vegas",
    circuitName: "Las Vegas Strip Circuit",
    location: "Las Vegas",
    country: "Etats-Unis",
    roundDate: "Novembre 2026",
    seasonPhase: "Fin de saison",
    accentColor: "#EC4899",
    gradient: "linear-gradient(90deg,#500724 0%,#BE185D 30%,#EC4899 65%,#F9A8D4 100%)",
    image: "/circuits/vegas.webp",
    lapRecord: "1:34.876",
    length: "6,201 km",
    laps: "50",
    firstGrandPrix: "2023",
    metaDescription: "Grand Prix de Las Vegas en novembre 2026 : course nocturne spectaculaire sur le Strip, longues lignes droites et show américain.",
    summary: [
      "Las Vegas mise sur une course nocturne ultra-visuelle au coeur du Strip et de ses longues lignes droites.",
      "La temperature souvent fraiche et les freinages appuyes creent une lecture assez specifique de la performance.",
      "Le circuit favorise les voitures efficaces en pointe tout en exposant fort l'usure au freinage.",
    ],
    stats: [
      { label: "Longueur", value: "6,201 km" },
      { label: "Tours", value: "50" },
      { label: "Record du tour", value: "1:34.876" },
      { label: "Premier GP", value: "2023" },
    ],
    highlights: [
      { label: "Decorum", value: "Unique", description: "Le Strip donne a la F1 un cadre tres different des autres courses." },
      { label: "Temperature", value: "Fraiche", description: "Les conditions nocturnes influencent la mise en temperature des pneus." },
      { label: "Vitesse", value: "Importante", description: "Les longues lignes droites mettent l'efficacite aero au premier plan." },
    ],
  },
  doha: {
    slug: "doha",
    grandPrix: "Grand Prix du Qatar",
    circuitName: "Lusail International Circuit",
    location: "Doha",
    country: "Qatar",
    roundDate: "Fin novembre 2026",
    seasonPhase: "Fin de saison",
    accentColor: "#8B5CF6",
    gradient: "linear-gradient(90deg,#2E1065 0%,#6D28D9 30%,#8B5CF6 65%,#DDD6FE 100%)",
    image: "/circuits/qatar.webp",
    lapRecord: "1:22.384",
    length: "5,419 km",
    laps: "57",
    firstGrandPrix: "2021",
    metaDescription: "Grand Prix du Qatar au Lusail International Circuit (Doha) fin novembre 2026 : un tracé rapide et fluide en fin de saison F1.",
    summary: [
      "Lusail est tres fluide et rapide, avec une serie de courbes moyennes et rapides qui sollicitent fort les pneus.",
      "Le vent et le sable peuvent compliquer la lecture de piste, surtout en debut de week-end.",
      "En fin de saison, ce rendez-vous peut devenir un moment cle pour boucler les championnats.",
    ],
    stats: [
      { label: "Longueur", value: "5,419 km" },
      { label: "Tours", value: "57" },
      { label: "Record du tour", value: "1:22.384" },
      { label: "Premier GP", value: "2021" },
    ],
    highlights: [
      { label: "Flux", value: "Rapide", description: "Les virages moyens et rapides demandent beaucoup de stabilite." },
      { label: "Pneus", value: "Sous pression", description: "Les appuis lateraux peuvent vite user les gommes." },
      { label: "Moment", value: "Tres tardif", description: "Le GP arrive au moment ou chaque detail compte encore plus." },
    ],
  },
  "yas-marina": {
    slug: "yas-marina",
    grandPrix: "Grand Prix d'Abou Dabi",
    circuitName: "Yas Marina",
    location: "Yas Marina",
    country: "Emirats arabes unis",
    roundDate: "6 decembre 2026",
    seasonPhase: "Fin de saison",
    accentColor: "#06B6D4",
    gradient: "linear-gradient(90deg,#083344 0%,#0E7490 30%,#06B6D4 65%,#A5F3FC 100%)",
    image: "/circuits/emirats-rarabes-unis.webp",
    lapRecord: "1:26.103",
    length: "5,281 km",
    laps: "58",
    firstGrandPrix: "2009",
    metaDescription: "Grand Prix d'Abou Dabi à Yas Marina le 6 décembre 2026 : la finale de la saison F1 2026, sous les projecteurs et pleine de dramaturgie.",
    summary: [
      "Abou Dabi cloture la saison 2026 avec un circuit moderne, large et tres suivi pour son final sous les projecteurs.",
      "Les longues lignes droites et les freinages appuyes doivent etre equilibres avec une bonne motricite dans le dernier secteur.",
      "Qu'il s'agisse d'un titre ou d'un dernier duel, Yas Marina porte toujours la dramaturgie de la fin d'exercice.",
    ],
    stats: [
      { label: "Longueur", value: "5,281 km" },
      { label: "Tours", value: "58" },
      { label: "Record du tour", value: "1:26.103" },
      { label: "Premier GP", value: "2009" },
    ],
    highlights: [
      { label: "Finale", value: "Saison 2026", description: "Le championnat se referme ici le 6 decembre 2026." },
      { label: "Cadre", value: "Nocturne", description: "La transition jour-nuit reste l'une des signatures visuelles du lieu." },
      { label: "Enjeu", value: "Derniere chance", description: "Le moindre point peut y valoir tres cher au classement final." },
    ],
  },
};

export const circuitMenu = Object.values(circuitPages).map((circuit) => ({
  slug: circuit.slug,
  grandPrix: circuit.grandPrix,
  circuitName: circuit.circuitName,
  date: circuit.roundDate,
}));
