export type DriverCareerHighlight = {
  year: string;
  title: string;
  description: string;
};

export type DriverStat = {
  label: string;
  value: string;
};

export type DriverPageData = {
  slug: string;
  name: string;
  image: string;
  number: string;
  teamName: string;
  teamSlug: string;
  teamLogo: string;
  accentColor: string;
  gradient: string;
  nationality: string;
  subtitle: string;
  age: string;
  metaDescription: string;
  bio: string[];
  stats: DriverStat[];
  highlights: DriverCareerHighlight[];
  emptyState?: {
    title: string;
    description: string;
    image: string;
  };
};

export const driverPages: Record<string, DriverPageData> = {
  "george-russell": {
    slug: "george-russell",
    name: "George Russell",
    image: "/drivers/russell.png",
    number: "63",
    teamName: "Mercedes",
    teamSlug: "mercedes",
    teamLogo: "/logos/mercedes.png",
    accentColor: "#00D2BE",
    gradient: "linear-gradient(90deg,#000000 0%,#004d46 20%,#00D2BE 60%,#66fff0 100%)",
    nationality: "Royaume-Uni",
    subtitle: "Pilote Mercedes",
    age: "28 ans",
    metaDescription: "George Russell (n°63), pilote Mercedes britannique : 6 victoires, 26 podiums et l'ambition d'un premier titre mondial en F1.",
    bio: [
      "George Russell s'est impose comme l'un des pilotes britanniques les plus solides de sa generation, avec une trajectoire construite autour de la vitesse pure et d'une grande regularite.",
      "Apres avoir brille dans les formules de promotion, il a debute en Formule 1 chez Williams avant de rejoindre Mercedes pour s'installer durablement dans le haut de grille.",
      "Il est aujourd'hui l'un des leaders du projet Mercedes et vise les victoires ainsi que la conquete d'un premier titre mondial.",
    ],
    stats: [
      { label: "Numero", value: "63" },
      { label: "Podiums", value: "26" },
      { label: "Victoires", value: "6" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2017", title: "Champion F3 Europe", description: "Il confirme son statut de grand espoir du sport automobile." },
      { year: "2018", title: "Champion F2", description: "Il remporte le titre des sa premiere saison dans l'antichambre de la F1." },
      { year: "2022", title: "Premiere victoire en F1", description: "Il ouvre son compteur en Grand Prix et s'affirme chez Mercedes." },
    ],
  },
  "kimi-antonelli": {
    slug: "kimi-antonelli",
    name: "Kimi Antonelli",
    image: "/drivers/antonelli.png",
    number: "12",
    teamName: "Mercedes",
    teamSlug: "mercedes",
    teamLogo: "/logos/mercedes.png",
    accentColor: "#00D2BE",
    gradient: "linear-gradient(90deg,#000000 0%,#004d46 20%,#00D2BE 60%,#66fff0 100%)",
    nationality: "Italie",
    subtitle: "Pilote Mercedes",
    age: "19 ans",
    metaDescription: "Kimi Antonelli (n°12), jeune prodige italien de Mercedes : déjà 5 podiums et 1 victoire à seulement 19 ans en Formule 1.",
    bio: [
      "Kimi Antonelli fait partie des plus grands espoirs de la nouvelle generation italienne. Sa progression fulgurante en karting et en monoplace l'a rapidement place sur le radar des meilleures equipes.",
      "Membre du programme Mercedes, il s'est distingue tres jeune par sa vitesse naturelle et sa capacite d'adaptation.",
      "Son objectif est de s'imposer durablement en Formule 1 et de devenir l'un des visages du projet Mercedes sur le long terme.",
    ],
    stats: [
      { label: "Numero", value: "12" },
      { label: "Podiums", value: "5" },
      { label: "Victoires", value: "1" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2022", title: "Sacres en formule junior", description: "Il accumule les titres et confirme son potentiel exceptionnel." },
      { year: "2024", title: "Ascension acceleree", description: "Il franchit les categories de promotion a grande vitesse." },
    ],
  },
  "lewis-hamilton": {
    slug: "lewis-hamilton",
    name: "Lewis Hamilton",
    image: "/drivers/hamilton.png",
    number: "44",
    teamName: "Ferrari",
    teamSlug: "ferrari",
    teamLogo: "/logos/ferrari.png",
    accentColor: "#DC0000",
    gradient: "linear-gradient(90deg,#000000 0%,#3a0000 10%,#990000 30%,#DC0000 70%,#ff1a1a 100%)",
    nationality: "Royaume-Uni",
    subtitle: "Pilote Ferrari",
    age: "41 ans",
    metaDescription: "Lewis Hamilton (n°44), septuple champion du monde chez Ferrari : 105 victoires et 203 podiums, la légende continue en F1.",
    bio: [
      "Lewis Hamilton est l'un des pilotes les plus marquants de l'histoire de la Formule 1, avec un palmares hors norme et une longivite exceptionnelle au plus haut niveau.",
      "Champion du monde a de multiples reprises, il a construit sa legende chez McLaren puis Mercedes avant de se lancer dans un nouveau chapitre avec Ferrari.",
      "Il reste une reference absolue par son experience, sa vitesse en course et sa capacite a faire progresser une equipe.",
    ],
    stats: [
      { label: "Numero", value: "44" },
      { label: "Podiums", value: "203" },
      { label: "Victoires", value: "105" },
      { label: "Titres mondiaux", value: "7" },
    ],
    highlights: [
      { year: "2008", title: "Premier titre mondial", description: "Il devient champion du monde avec McLaren." },
      { year: "2014", title: "Deuxieme titre mondial", description: "Il lance l'ere dominante de Mercedes." },
      { year: "2015", title: "Troisieme titre mondial", description: "Il confirme sa suprematie dans l'ere hybride." },
      { year: "2017", title: "Quatrieme titre mondial", description: "Il reprend le controle du championnat avec Mercedes." },
      { year: "2018", title: "Cinquieme titre mondial", description: "Il rejoint les plus grands noms de la discipline." },
      { year: "2019", title: "Sixieme titre mondial", description: "Il se rapproche encore du record absolu." },
      { year: "2020", title: "Septieme titre mondial", description: "Il egale le record historique de titres pilotes." },
    ],
  },
  "charles-leclerc": {
    slug: "charles-leclerc",
    name: "Charles Leclerc",
    image: "/drivers/leclerc.png",
    number: "16",
    teamName: "Ferrari",
    teamSlug: "ferrari",
    teamLogo: "/logos/ferrari.png",
    accentColor: "#DC0000",
    gradient: "linear-gradient(90deg,#000000 0%,#3a0000 10%,#990000 30%,#DC0000 70%,#ff1a1a 100%)",
    nationality: "Monaco",
    subtitle: "Pilote Ferrari",
    age: "28 ans",
    metaDescription: "Charles Leclerc (n°16), pilote Ferrari monégasque : 8 victoires et 51 podiums, l'un des plus rapides sur un tour de la grille.",
    bio: [
      "Charles Leclerc est l'un des pilotes les plus rapides sur un tour de la grille et l'un des symboles de la nouvelle generation Ferrari.",
      "Champion en GP3 puis en F2, il a impressionne des ses debuts en Formule 1 avant de rejoindre la Scuderia.",
      "Son ambition est claire: ramener Ferrari au sommet et transformer son potentiel en titre mondial.",
    ],
    stats: [
      { label: "Numero", value: "16" },
      { label: "Podiums", value: "51" },
      { label: "Victoires", value: "8" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2017", title: "Champion F2", description: "Il s'impose dans la categorie preparatoire des sa premiere tentative." },
      { year: "2019", title: "Premieres victoires Ferrari", description: "Il gagne a Spa et Monza et devient un chouchou des tifosi." },
      { year: "2022", title: "Lutte pour le titre", description: "Il s'installe durablement parmi les references de la grille." },
    ],
  },
  "lando-norris": {
    slug: "lando-norris",
    name: "Lando Norris",
    image: "/drivers/norris.png",
    number: "1",
    teamName: "McLaren",
    teamSlug: "mclaren",
    teamLogo: "/logos/mclaren.png",
    accentColor: "#FF8700",
    gradient: "linear-gradient(90deg,#000000 0%,#4d2a00 20%,#FF8700 60%,#ffb347 100%)",
    nationality: "Royaume-Uni",
    subtitle: "Pilote McLaren",
    age: "26 ans",
    metaDescription: "Lando Norris (n°1), champion du monde 2025 avec McLaren : 11 victoires et 44 podiums, le nouveau leader de la F1.",
    bio: [
      "Lando Norris s'est impose comme le visage de la renaissance de McLaren apres plusieurs saisons de progression constante.",
      "Reconnu pour sa vitesse pure, sa regularite et son sens de l'attaque, il a franchi un cap decisif en devenant champion du monde 2025.",
      "Il aborde desormais la saison 2026 avec le numero 1 et le statut de reference du paddock.",
    ],
    stats: [
      { label: "Numero", value: "1" },
      { label: "Podiums", value: "44" },
      { label: "Victoires", value: "11" },
      { label: "Titres mondiaux", value: "1" },
    ],
    highlights: [
      { year: "2018", title: "Champion F2 vice-champion", description: "Il confirme son potentiel en monoplace avant la F1." },
      { year: "2021", title: "Saison de reference", description: "Il s'installe comme leader naturel chez McLaren." },
      { year: "2024", title: "Cap franchi", description: "Il transforme sa regularite en victoires et en ambitions mondiales." },
      { year: "2025", title: "Champion du monde", description: "Il offre a McLaren son premier titre pilotes depuis 2008." },
    ],
  },
  "oscar-piastri": {
    slug: "oscar-piastri",
    name: "Oscar Piastri",
    image: "/drivers/piastri.png",
    number: "81",
    teamName: "McLaren",
    teamSlug: "mclaren",
    teamLogo: "/logos/mclaren.png",
    accentColor: "#FF8700",
    gradient: "linear-gradient(90deg,#000000 0%,#4d2a00 20%,#FF8700 60%,#ffb347 100%)",
    nationality: "Australie",
    subtitle: "Pilote McLaren",
    age: "24 ans",
    metaDescription: "Oscar Piastri (n°81), pilote McLaren australien : 9 victoires et 26 podiums, l'un des talents les plus complets de la grille.",
    bio: [
      "Oscar Piastri s'est fait remarquer par un parcours exceptionnel dans les categories juniors, avec des titres remportes en serie avant meme son arrivee en Formule 1.",
      "Chez McLaren, il s'est rapidement adapte au rythme de la discipline et a montre une grande maturite en course.",
      "Sa campagne 2025, conclue avec plusieurs victoires et une vraie lutte interne pour le titre, a confirme qu'il fait partie des pilotes les plus complets de sa generation.",
    ],
    stats: [
      { label: "Numero", value: "81" },
      { label: "Podiums", value: "26" },
      { label: "Victoires", value: "9" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2020", title: "Champion F3", description: "Il remporte le titre des sa premiere saison." },
      { year: "2021", title: "Champion F2", description: "Il confirme son statut de futur grand de la F1." },
      { year: "2024", title: "Premieres victoires", description: "Il s'impose parmi les pilotes capables de gagner regulierement." },
      { year: "2025", title: "Saison de la confirmation", description: "Il remporte sept Grands Prix et reste en lice pour le titre jusqu'au bout." },
    ],
  },
  "max-verstappen": {
    slug: "max-verstappen",
    name: "Max Verstappen",
    image: "/drivers/verstappen.png",
    number: "3",
    teamName: "Red Bull Racing",
    teamSlug: "redbull",
    teamLogo: "/logos/redbull.png",
    accentColor: "#0600EF",
    gradient: "linear-gradient(90deg,#000000 0%,#02006b 20%,#0600EF 60%,#4d4dff 100%)",
    nationality: "Pays-Bas",
    subtitle: "Pilote Red Bull Racing",
    age: "28 ans",
    metaDescription: "Max Verstappen (n°3), quadruple champion du monde chez Red Bull Racing : 71 victoires et 127 podiums, référence de la F1.",
    bio: [
      "Max Verstappen est l'une des figures dominantes de l'ere moderne de la Formule 1.",
      "Precoce des son arrivee dans la discipline, il est devenu le plus jeune vainqueur de Grand Prix puis a construit un impressionnant palmares avec Red Bull Racing.",
      "Sa vitesse, sa constance et son agressivite maitrisee en font une reference absolue du championnat.",
    ],
    stats: [
      { label: "Numero", value: "3" },
      { label: "Podiums", value: "127" },
      { label: "Victoires", value: "71" },
      { label: "Titres mondiaux", value: "4" },
    ],
    highlights: [
      { year: "2016", title: "Premiere victoire", description: "Il gagne des sa premiere course avec Red Bull." },
      { year: "2021", title: "Premier titre mondial", description: "Il conquiert enfin la couronne mondiale." },
      { year: "2022", title: "Deuxieme titre mondial", description: "Il confirme son nouveau statut de patron du championnat." },
      { year: "2023", title: "Troisieme titre mondial", description: "Il domine une saison historique avec Red Bull." },
      { year: "2024", title: "Quatrieme titre mondial", description: "Il confirme sa domination sur l'ere recente." },
    ],
  },
  "isack-hadjar": {
    slug: "isack-hadjar",
    name: "Isack Hadjar",
    image: "/drivers/hadjar.png",
    number: "6",
    teamName: "Red Bull Racing",
    teamSlug: "redbull",
    teamLogo: "/logos/redbull.png",
    accentColor: "#0600EF",
    gradient: "linear-gradient(90deg,#000000 0%,#02006b 20%,#0600EF 60%,#4d4dff 100%)",
    nationality: "France",
    subtitle: "Pilote Red Bull Racing",
    age: "21 ans",
    metaDescription: "Isack Hadjar (n°6), jeune pilote français de Red Bull Racing : premier podium au GP des Pays-Bas 2025, l'un des espoirs de la F1.",
    bio: [
      "Isack Hadjar represente la nouvelle vague du programme Red Bull. Sa progression en filiere junior lui a permis de se faire une place parmi les jeunes pilotes les plus suivis.",
      "Rapide et agressif, il s'est forge une reputation de pilote spectaculaire en monoplace.",
      "Sa premiere saison complete en Formule 1 a ete marquee par un premier podium au Grand Prix des Pays-Bas 2025, preuve concrete de son potentiel au plus haut niveau.",
    ],
    stats: [
      { label: "Numero", value: "6" },
      { label: "Podiums", value: "1" },
      { label: "Victoires", value: "0" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2022", title: "Montee en puissance", description: "Il s'impose comme l'un des juniors les plus prometteurs de Red Bull." },
      { year: "2024", title: "Accession a la F1", description: "Il franchit un cap important dans sa carriere." },
      { year: "2025", title: "Premier podium en F1", description: "Il termine troisieme du Grand Prix des Pays-Bas a Zandvoort." },
    ],
  },
  "fernando-alonso": {
    slug: "fernando-alonso",
    name: "Fernando Alonso",
    image: "/drivers/alonso.png",
    number: "14",
    teamName: "Aston Martin",
    teamSlug: "aston-martin",
    teamLogo: "/logos/astonmartin.png",
    accentColor: "#006F62",
    gradient: "linear-gradient(90deg,#000000 0%,#00352F 20%,#006F62 60%,#00A19B 100%)",
    nationality: "Espagne",
    subtitle: "Pilote Aston Martin",
    age: "44 ans",
    metaDescription: "Fernando Alonso (n°14), double champion du monde chez Aston Martin : 32 victoires et 106 podiums, l'un des plus grands pilotes.",
    bio: [
      "Fernando Alonso est l'un des pilotes les plus experimentes et les plus respectes de l'histoire recente de la Formule 1.",
      "Double champion du monde avec Renault, il a ensuite poursuivi une carriere exceptionnelle marquee par sa polyvalence et sa science de la course.",
      "Toujours redoutable, il apporte a Aston Martin un melange unique d'experience, de vitesse et de leadership.",
    ],
    stats: [
      { label: "Numero", value: "14" },
      { label: "Podiums", value: "106" },
      { label: "Victoires", value: "32" },
      { label: "Titres mondiaux", value: "2" },
    ],
    highlights: [
      { year: "2005", title: "Premier titre mondial", description: "Il met fin a la domination de Schumacher avec Renault." },
      { year: "2006", title: "Deuxieme titre mondial", description: "Il confirme son rang parmi les plus grands." },
      { year: "2023", title: "Retour des podiums", description: "Il ramene Aston Martin sur le devant de la scene." },
    ],
  },
  "lance-stroll": {
    slug: "lance-stroll",
    name: "Lance Stroll",
    image: "/drivers/stroll.png",
    number: "18",
    teamName: "Aston Martin",
    teamSlug: "aston-martin",
    teamLogo: "/logos/astonmartin.png",
    accentColor: "#006F62",
    gradient: "linear-gradient(90deg,#000000 0%,#00352F 20%,#006F62 60%,#00A19B 100%)",
    nationality: "Canada",
    subtitle: "Pilote Aston Martin",
    age: "27 ans",
    metaDescription: "Lance Stroll (n°18), pilote canadien d'Aston Martin : 3 podiums en Formule 1 et l'ambition de franchir un nouveau cap.",
    bio: [
      "Lance Stroll a debute tres jeune en Formule 1 et a montre sa capacite a signer de gros resultats dans des contextes parfois delicats.",
      "Au fil des saisons, il a accumule de l'experience et plusieurs podiums, tout en participant a la construction du projet Aston Martin.",
      "Il cherche desormais a franchir un nouveau cap en regularite et en performance pure.",
    ],
    stats: [
      { label: "Numero", value: "18" },
      { label: "Podiums", value: "3" },
      { label: "Victoires", value: "0" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2016", title: "Champion F3 Europe", description: "Il se revele comme l'un des talents precoces de sa generation." },
      { year: "2017", title: "Premier podium en F1", description: "Il devient l'un des plus jeunes pilotes a monter sur un podium." },
    ],
  },
  "oliver-bearman": {
    slug: "oliver-bearman",
    name: "Oliver Bearman",
    image: "/drivers/bearman.png",
    number: "87",
    teamName: "Haas",
    teamSlug: "haas",
    teamLogo: "/logos/haas.png",
    accentColor: "#E6002B",
    gradient: "linear-gradient(90deg,#000000 0%,#4d0012 20%,#E6002B 60%,#ff3355 100%)",
    nationality: "Royaume-Uni",
    subtitle: "Pilote Haas",
    age: "21 ans",
    metaDescription: "Oliver Bearman (n°87), jeune pilote britannique de Haas issu de la filière Ferrari, l'un des espoirs à suivre en F1.",
    bio: [
      "Oliver Bearman est l'un des jeunes pilotes britanniques les plus suivis du paddock.",
      "Issu de la filiere Ferrari, il s'est fait remarquer par sa vitesse en formules de promotion et sa capacite a etre performant rapidement.",
      "Chez Haas, il dispose d'un terrain ideal pour apprendre la Formule 1 et construire sa reputation.",
    ],
    stats: [
      { label: "Numero", value: "87" },
      { label: "Podiums", value: "0" },
      { label: "Victoires", value: "0" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2021", title: "Champion F4 Italienne", description: "Il signe un premier grand titre en monoplace." },
      { year: "2024", title: "Premiers pas remarqués", description: "Il montre qu'il peut repondre present au plus haut niveau." },
    ],
  },
  "esteban-ocon": {
    slug: "esteban-ocon",
    name: "Esteban Ocon",
    image: "/drivers/ocon.png",
    number: "31",
    teamName: "Haas",
    teamSlug: "haas",
    teamLogo: "/logos/haas.png",
    accentColor: "#E6002B",
    gradient: "linear-gradient(90deg,#000000 0%,#4d0012 20%,#E6002B 60%,#ff3355 100%)",
    nationality: "France",
    subtitle: "Pilote Haas",
    age: "29 ans",
    metaDescription: "Esteban Ocon (n°31), pilote français de Haas : vainqueur du GP de Hongrie 2021, 4 podiums au compteur en Formule 1.",
    bio: [
      "Esteban Ocon s'est construit un parcours solide en Formule 1, marque par sa combativite et sa capacite a maximiser les opportunites.",
      "Vainqueur d'un Grand Prix avec Alpine, il s'est impose comme un pilote fiable et capable de briller dans des conditions compliquees.",
      "Son experience constitue un vrai atout pour une equipe en phase de progression.",
    ],
    stats: [
      { label: "Numero", value: "31" },
      { label: "Podiums", value: "4" },
      { label: "Victoires", value: "1" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2014", title: "Champion F3 Europe", description: "Il remporte l'un des championnats juniors les plus releves." },
      { year: "2021", title: "Victoire en Hongrie", description: "Il signe sa premiere victoire en Formule 1." },
    ],
  },
  "liam-lawson": {
    slug: "liam-lawson",
    name: "Liam Lawson",
    image: "/drivers/lawson.png",
    number: "30",
    teamName: "Racing Bulls",
    teamSlug: "rb",
    teamLogo: "/logos/rb.png",
    accentColor: "#1E41FF",
    gradient: "linear-gradient(90deg,#000000 0%,#0B1A5A 20%,#1E41FF 60%,#4c6fff 100%)",
    nationality: "Nouvelle-Zelande",
    subtitle: "Pilote Racing Bulls",
    age: "24 ans",
    metaDescription: "Liam Lawson (n°30), pilote néo-zélandais de Racing Bulls issu de la filière Red Bull, rapide dès sa première saison en F1.",
    bio: [
      "Liam Lawson est un produit de la filiere Red Bull connu pour sa capacite a etre rapide sans long temps d'adaptation.",
      "Il s'est illustre dans plusieurs championnats de promotion et a saisi chaque opportunite offerte pour se rapprocher d'un volant durable en F1.",
      "Chez RB, il peut continuer a prouver qu'il merite une place dans l'ecosysteme Red Bull.",
    ],
    stats: [
      { label: "Numero", value: "30" },
      { label: "Podiums", value: "0" },
      { label: "Victoires", value: "0" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2022", title: "Polyvalence en formule promotion", description: "Il multiplie les performances dans plusieurs series." },
      { year: "2023", title: "Remplacements convaincants", description: "Il profite de ses chances pour se faire remarquer." },
    ],
  },
  "arvid-lindblad": {
    slug: "arvid-lindblad",
    name: "Arvid Lindblad",
    image: "/drivers/lindblad.png",
    number: "41",
    teamName: "Racing Bulls",
    teamSlug: "rb",
    teamLogo: "/logos/rb.png",
    accentColor: "#1E41FF",
    gradient: "linear-gradient(90deg,#000000 0%,#0B1A5A 20%,#1E41FF 60%,#4c6fff 100%)",
    nationality: "Royaume-Uni",
    subtitle: "Pilote Racing Bulls",
    age: "18 ans",
    metaDescription: "Arvid Lindblad (n°41), l'un des plus jeunes talents du programme Red Bull chez Racing Bulls, à seulement 18 ans.",
    bio: [
      "Arvid Lindblad fait partie des tres jeunes talents surveilles de pres par le programme Red Bull.",
      "Ses performances en karting puis en monoplace ont rapidement renforce sa reputation de pilote offensif et naturellement rapide.",
      "Son arrivee dans l'univers de la F1 s'inscrit dans une logique de developpement a fort potentiel.",
    ],
    stats: [
      { label: "Numero", value: "41" },
      { label: "Podiums", value: "0" },
      { label: "Victoires", value: "0" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2023", title: "Percée en junior", description: "Il s'installe parmi les espoirs les plus suivis du paddock." },
      { year: "2025", title: "Cap vers la F1", description: "Il se rapproche concretement d'un role durable en Grand Prix." },
    ],
  },
  "nico-hulkenberg": {
    slug: "nico-hulkenberg",
    name: "Nico Hulkenberg",
    image: "/drivers/hulkenberg.png",
    number: "27",
    teamName: "Audi",
    teamSlug: "audi",
    teamLogo: "/logos/audi.png",
    accentColor: "#BB0A30",
    gradient: "linear-gradient(90deg,#000000 0%,#6b001c 25%,#BB0A30 60%,#ff244f 100%)",
    nationality: "Allemagne",
    subtitle: "Pilote Audi",
    age: "38 ans",
    metaDescription: "Nico Hulkenberg (n°27), pilote allemand d'Audi et ex-champion GP2 : premier podium F1 obtenu en 2025 après des années d'expérience.",
    bio: [
      "Nico Hulkenberg est l'un des pilotes les plus experimentes de la grille et un technicien reconnu pour sa capacite a faire progresser une equipe.",
      "Champion GP2 avant la Formule 1, il a construit une carriere solide faite de regularite et de grosses performances en qualification.",
      "Son role chez Audi est central pour accompagner la montee en puissance du projet.",
    ],
    stats: [
      { label: "Numero", value: "27" },
      { label: "Podiums", value: "1" },
      { label: "Victoires", value: "0" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2009", title: "Champion GP2", description: "Il arrive en F1 avec une solide reputation de futur grand." },
      { year: "2015", title: "Victoire au Mans", description: "Il ajoute un succes majeur en endurance a son CV." },
      { year: "2025", title: "Premier podium en F1", description: "Il debloque enfin son compteur podiums en Grand Prix." },
    ],
  },
  "gabriel-bortoleto": {
    slug: "gabriel-bortoleto",
    name: "Gabriel Bortoleto",
    image: "/drivers/bortoleto.png",
    number: "5",
    teamName: "Audi",
    teamSlug: "audi",
    teamLogo: "/logos/audi.png",
    accentColor: "#BB0A30",
    gradient: "linear-gradient(90deg,#000000 0%,#6b001c 25%,#BB0A30 60%,#ff244f 100%)",
    nationality: "Bresil",
    subtitle: "Pilote Audi",
    age: "21 ans",
    metaDescription: "Gabriel Bortoleto (n°5), jeune pilote brésilien d'Audi, l'un des talents les plus prometteurs de sa génération en Formule 1.",
    bio: [
      "Gabriel Bortoleto s'est impose comme l'un des jeunes pilotes bresiliens les plus prometteurs de sa generation.",
      "Sa progression en junior a mis en avant son intelligence de course et sa capacite a etre performant sur la duree d'un championnat.",
      "Son association avec Audi peut lui offrir un environnement ideal pour grandir en Formule 1.",
    ],
    stats: [
      { label: "Numero", value: "5" },
      { label: "Podiums", value: "0" },
      { label: "Victoires", value: "0" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2023", title: "Titre en categorie junior", description: "Il confirme qu'il fait partie des talents a suivre." },
      { year: "2025", title: "Transition vers la F1", description: "Il prepare son installation au plus haut niveau." },
    ],
  },
  "pierre-gasly": {
    slug: "pierre-gasly",
    name: "Pierre Gasly",
    image: "/drivers/gasly.png",
    number: "10",
    teamName: "Alpine",
    teamSlug: "alpine",
    teamLogo: "/logos/alpine.png",
    accentColor: "#002A5C",
    gradient: "linear-gradient(90deg,#000000 0%,#002A5C 20%,#0090FF 60%,#00AEEF 100%)",
    nationality: "France",
    subtitle: "Pilote Alpine",
    age: "30 ans",
    metaDescription: "Pierre Gasly (n°10), pilote français d'Alpine, vainqueur du GP d'Italie 2020 à Monza et ex-champion GP2.",
    bio: [
      "Pierre Gasly est l'un des pilotes francais les plus experimentes de la grille actuelle.",
      "Champion GP2, il a connu plusieurs etapes importantes dans l'univers Red Bull avant de se relancer et de gagner en Italie avec AlphaTauri.",
      "Chez Alpine, il apporte son experience du haut niveau et sa capacite a maximiser les opportunites.",
    ],
    stats: [
      { label: "Numero", value: "10" },
      { label: "Podiums", value: "5" },
      { label: "Victoires", value: "1" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2016", title: "Champion GP2", description: "Il decroche le titre avant d'integrer durablement la F1." },
      { year: "2020", title: "Victoire a Monza", description: "Il signe l'un des succes les plus marquants de sa carriere." },
    ],
  },
  "franco-colapinto": {
    slug: "franco-colapinto",
    name: "Franco Colapinto",
    image: "/drivers/colapinto.png",
    number: "43",
    teamName: "Alpine",
    teamSlug: "alpine",
    teamLogo: "/logos/alpine.png",
    accentColor: "#002A5C",
    gradient: "linear-gradient(90deg,#000000 0%,#002A5C 20%,#0090FF 60%,#00AEEF 100%)",
    nationality: "Argentine",
    subtitle: "Pilote Alpine",
    age: "22 ans",
    metaDescription: "Franco Colapinto (n°43), pilote argentin d'Alpine qui incarne le retour de l'Argentine sur la grille de Formule 1.",
    bio: [
      "Franco Colapinto incarne le retour d'une forte presence argentine dans l'univers des monoplaces internationales.",
      "Son parcours en formules de promotion a mis en valeur sa vitesse de base et sa capacite a saisir les opportunites.",
      "Au sein du projet Alpine, il peut se construire progressivement une vraie place en Formule 1.",
    ],
    stats: [
      { label: "Numero", value: "43" },
      { label: "Podiums", value: "0" },
      { label: "Victoires", value: "0" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2023", title: "Progression en formule junior", description: "Il se rapproche de plus en plus des standards de la F1." },
      { year: "2025", title: "Cap superieur", description: "Il integre un projet d'usine ambitieux avec Alpine." },
    ],
  },
  "alexander-albon": {
    slug: "alexander-albon",
    name: "Alexander Albon",
    image: "/drivers/albon.png",
    number: "23",
    teamName: "Williams",
    teamSlug: "williams",
    teamLogo: "/logos/williams.png",
    accentColor: "#005AFF",
    gradient: "linear-gradient(90deg,#000000 0%,#002b73 20%,#005AFF 60%,#6aa3ff 100%)",
    nationality: "Thailande",
    subtitle: "Pilote Williams",
    age: "30 ans",
    metaDescription: "Alexander Albon (n°23), pilote thaïlandais de Williams : 2 podiums et un rôle clé dans la reconstruction de l'équipe.",
    bio: [
      "Alexander Albon s'est relance avec succes chez Williams apres un debut de carriere mouvemente dans l'univers Red Bull.",
      "Il est reconnu pour sa capacite a tirer le maximum d'une voiture difficile et pour sa regularite en course.",
      "Son leadership a joue un role important dans la reconstruction de l'equipe britannique.",
    ],
    stats: [
      { label: "Numero", value: "23" },
      { label: "Podiums", value: "2" },
      { label: "Victoires", value: "0" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2018", title: "Vice-champion F2", description: "Il gagne rapidement sa place dans le paddock F1." },
      { year: "2022", title: "Relance chez Williams", description: "Il devient la reference sportive de l'equipe." },
    ],
  },
  "carlos-sainz": {
    slug: "carlos-sainz",
    name: "Carlos Sainz",
    image: "/drivers/sainz.png",
    number: "55",
    teamName: "Williams",
    teamSlug: "williams",
    teamLogo: "/logos/williams.png",
    accentColor: "#005AFF",
    gradient: "linear-gradient(90deg,#000000 0%,#002b73 20%,#005AFF 60%,#6aa3ff 100%)",
    nationality: "Espagne",
    subtitle: "Pilote Williams",
    age: "31 ans",
    metaDescription: "Carlos Sainz (n°55), pilote espagnol de Williams : 4 victoires et 29 podiums, passé par Ferrari, McLaren et Renault.",
    bio: [
      "Carlos Sainz s'est forge une reputation de pilote complet, rapide et tres serieux dans sa preparation.",
      "Passe par Toro Rosso, Renault, McLaren puis Ferrari, il a montre qu'il pouvait etre performant dans des environnements tres differents.",
      "Son experience et sa finesse technique constituent un atout majeur pour une equipe ambitieuse.",
    ],
    stats: [
      { label: "Numero", value: "55" },
      { label: "Podiums", value: "29" },
      { label: "Victoires", value: "4" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2022", title: "Premiere victoire", description: "Il debloque son compteur en Grand Prix." },
      { year: "2024", title: "Pilote de reference", description: "Il confirme son statut de valeur sure de la grille." },
    ],
  },
  "sergio-perez": {
    slug: "sergio-perez",
    name: "Sergio Perez",
    image: "/drivers/perez.png",
    number: "11",
    teamName: "Cadillac",
    teamSlug: "cadillac",
    teamLogo: "/logos/cadillac.png",
    accentColor: "#003A8F",
    gradient: "linear-gradient(90deg,#000000 0%,#001d4d 20%,#003A8F 60%,#3c6cff 100%)",
    nationality: "Mexique",
    subtitle: "Pilote Cadillac",
    age: "36 ans",
    metaDescription: "Sergio Perez (n°11), pilote mexicain expérimenté de Cadillac : 6 victoires et 39 podiums acquis en Formule 1.",
    bio: [
      "Sergio Perez a longtemps ete l'un des meilleurs specialistes du management des pneus et des courses opportunistes.",
      "Avec plusieurs victoires et une solide experience dans le haut de grille, il apporte une vraie expertise technique a chaque projet.",
      "Dans une structure naissante, son profil de pilote chevronne a une valeur particuliere.",
    ],
    stats: [
      { label: "Numero", value: "11" },
      { label: "Podiums", value: "39" },
      { label: "Victoires", value: "6" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2020", title: "Premiere victoire", description: "Il gagne enfin apres des annees de persistance en F1." },
      { year: "2023", title: "Role cle en haut de grille", description: "Il confirme sa place parmi les pilotes les plus experimentes." },
    ],
  },
  "valtteri-bottas": {
    slug: "valtteri-bottas",
    name: "Valtteri Bottas",
    image: "/drivers/bottas.png",
    number: "77",
    teamName: "Cadillac",
    teamSlug: "cadillac",
    teamLogo: "/logos/cadillac.png",
    accentColor: "#003A8F",
    gradient: "linear-gradient(90deg,#000000 0%,#001d4d 20%,#003A8F 60%,#3c6cff 100%)",
    nationality: "Finlande",
    subtitle: "Pilote Cadillac",
    age: "36 ans",
    metaDescription: "Valtteri Bottas (n°77), pilote finlandais de Cadillac : 10 victoires et 67 podiums acquis chez Mercedes, forte expérience.",
    bio: [
      "Valtteri Bottas est un pilote d'experience qui a connu plusieurs saisons au sein d'une equipe championne du monde.",
      "Sa vitesse en qualification et sa capacite a travailler dans un cadre technique exigeant ont fait de lui une valeur sure du paddock.",
      "Il peut jouer un role structurant dans le developpement d'une nouvelle equipe.",
    ],
    stats: [
      { label: "Numero", value: "77" },
      { label: "Podiums", value: "67" },
      { label: "Victoires", value: "10" },
      { label: "Titres mondiaux", value: "0" },
    ],
    highlights: [
      { year: "2017", title: "Premiere victoire", description: "Il remporte son premier Grand Prix avec Mercedes." },
      { year: "2019", title: "Saison solide", description: "Il signe plusieurs victoires dans une equipe de pointe." },
    ],
  },
};

export const driverMenu = Object.values(driverPages).map((driver) => ({
  name: driver.name,
  slug: driver.slug,
  img: driver.image,
}));
